#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/d1
#    username: root
#    password: root
#    driver-class-name: com.mysql.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
##    druid:
#    initial-size: 50 # 连接池初始化时创建的连接数。默认值为0。
#    min-idle: 50 # 连接池中保持的最小空闲连接数量。当连接池中的连接数量小于这个值时，连接池会尝试创建新的连接。默认值为0。
#    max-active: 200 # 连接池中允许的最大连接数。如果所有连接都被使用并且没有空闲连接，新的连接请求将被阻塞，直到有连接可用。默认值为8。
#    max-wait: 60000 # 获取连接时的最大等待时间，单位为毫秒。如果在指定的时间内无法获取到连接，将抛出异常。默认值为-1，表示无限等待。
#    time-between-eviction-runs-millis: 60000 # 连接池每次检测空闲连接的间隔时间，单位为毫秒。默认值为60000毫秒（1分钟）。
#    min-evictable-idle-time-millis: 300000 # 连接在连接池中的最小空闲时间，超过这个时间的连接将被回收，单位为毫秒。默认值为300000毫秒（5分钟）。
#    max-evictable-idle-time-millis: 300000
#    validation-query: SELECT 1 # 用于验证连接是否有效的SQL查询语句。Druid会定期执行此查询来检测连接的可用性。默认为"SELECT 1"。
#    test-while-idle: true # 是否在连接空闲时检测连接的有效性。如果设置为true，则连接池会定期检测空闲连接，如果连接失效，将被标记为不可用并移除。默认为true。
#    test-on-borrow: false # 是否在从连接池借用连接时检测连接的有效性。如果设置为true，每次从连接池借用连接时都会执行连接有效性检测。默认为false。
#    test-on-return: false # 是否在归还连接到连接池时检测连接的有效性。如果设置为true，连接在归还到连接池时会进行有效性检测。默认为false。
#    pool-prepared-statements: true # 是否开启预处理语句池。预处理语句池可以提高性能，特别是在执行相同SQL语句多次时。默认为true。
#    max-pool-prepared-statement-per-connection-size: 20 #每个连接上允许的最大预处理语句数。默认值为20。
#    keep-alive: true
#    query-timeout: 6000
#    default-read-only: false
#    filters: config,stat,wall,slf4j
#    stat-view-servlet:
#      enabled: true
#      login-username: admin
#      login-password: admin
#      url-pattern: /durid/*
#

# DataSource Config
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/d1
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initialSize: 50 # 初始化连接池大小
      minIdle: 50 # 最小连接数
      maxActive: 200 # 最大连接数
      max-wait: 60000 # 单位ms 1分钟内无法获取到连接抛出异常。默认值-1 无限等待。
      time-between-eviction-runs-millis: 60000 # 单位ms 连接池每次检测空闲连接的间隔时间，默认1分钟。
      min-evictable-idle-time-millis: 300000 # 单位ms 空闲5分钟的连接将被回收
      validation-query: SELECT 1 # 定期执行此查询来检测连接的可用性，默认"SELECT 1"。
      test-while-idle: true # 连接空闲时检测连接的有效性，定期检测空闲连接，如果连接失效，就标记为不可用并移除。默认 true。
      test-on-borrow: false # 每次从连接池拿连接时检测连接的有效性。默认 false。
      test-on-return: false # 每次归还连接到连接池时检测连接的有效性。默认 false。
      pool-prepared-statements: true # 开启预处理语句池。在执行相同SQL语句多次时，提高性能。默认 true。
      max-pool-prepared-statement-per-connection-size: 20 # 每个连接上允许的最大预处理语句数。默认 20。
      web-stat-filter: #配置过滤器，过滤掉静态文件
        enabled: true
        url-pattern: /*
        exclusions: /druid/*,*.js,*.css,*.gif,*.jpg,*.bmp,*.png,*.ico
      stat-view-servlet: #配置可视化控制台页面
        enabled: true
        url-pattern: /druid/*
        allow: #IP白名单 没有配置或者为空 则允许所有访问
        deny:  #IP黑名单 若白名单也存在 则优先使用
        reset-enable: true #禁用重置按钮
        login-username: admin
        login-password: admin

# MyBatis配置
mybatis-plus:
  global-config:
    banner: false
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

